version: '3.8'
services:
  next-app:
    build: .
    image: next-app:latest
    container_name: next-app
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
    # do NOT necessarily expose to host; NPM will proxy via Docker network
    # If you must expose for debugging, uncomment ports:
    # ports:
    #   - "3000:3000"
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: "gen21network"
