version: '3.8'
services:
  next-app:
    build: .
    image: next-app:latest
    container_name: next-app
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - gen21network

networks:
  gen21network:
    external: true
